{
 "title": "PrivateBin Access Log",
 "tags": [
  "loki",
  "privatebin"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "label_name",
    "label": "Label Name",
    "query": {}
   },
   {
    "name": "label_value",
    "label": "Label Value",
    "query": {}
   },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Total Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Created Paste",
   "type": "stat",
   "description": "PrivateBin POST request may contain both a created paste and post requests for discussion comments. Since the URL remains the same, it's not possible to determine whether it's a paste or a discussion comment. If you intend to use this dashboard, it is recommended to disable discussions, as this can lead to incorrect results.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_method=\"POST\" | status=~\"200|201|202|204\" | accept=~\".*application/json.*\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Total Requested Paste",
   "type": "stat",
   "description": "This can include both expired and unexpired paste requests.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_uri=~\".*pasteid=.*\" | request_method=\"GET\" | accept=~\".*application/json.*\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Paste - Total Body Bytes Send",
   "type": "stat",
   "description": "This can include both expired and unexpired paste requests.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_method=~\"GET|POST\" | accept=~\".*application/json.*\" | unwrap body_bytes_sent |  __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Access Log Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "options": {
    "content": "# PrivateBin Access Log\n\nCreated by [VoidQuark](https://voidquark.com)\n\n- [Dashboard Source](https://github.com/voidquark/grafana-dashboards)\n\n- Follow me on [Twitter](https://twitter.com/voidquark) for updates on new and current dashboards."
   }
  },
  {
   "title": "Total Created Paste - Unique IP",
   "type": "stat",
   "description": "PrivateBin POST request may contain both a created paste and post requests for discussion comments. Since the URL remains the same, it's not possible to determine whether it's a paste or a discussion comment. If you intend to use this dashboard, it is recommended to disable discussions, as this can lead to incorrect results.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by(cf_connecting_ip) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_method=\"POST\" | status=~\"200|201|202|204\" | accept=~\".*application/json.*\" | __error__=\"\" [$__range])))",
     "legendFormat": "{{ cf_connecting_ip }}"
    }
   ]
  },
  {
   "title": "Total Requested Paste - Unique IP",
   "type": "stat",
   "description": "This can include both expired and unexpired paste requests.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by(cf_connecting_ip) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_uri=~\".*pasteid=.*\" | request_method=\"GET\" | accept=~\".*application/json.*\" | __error__=\"\" [$__range])))",
     "legendFormat": "{{ cf_connecting_ip }}"
    }
   ]
  },
  {
   "title": "Total Request 4xx",
   "type": "stat",
   "description": "This counter includes all 4xx requests for all types of requests, not just paste requests.",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | status=~\"4.+\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Total Request 5xx",
   "type": "stat",
   "description": "This counter includes all 5xx requests for all types of requests, not just paste requests.",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | status=~\"5.+\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Access Log in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Paste - Privatebin Recent Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_uri=~\".*pasteid=.*\" | request_method=\"GET\" | accept=~\".*application/json.*\" | line_format \"📜 {{.request_method}} 📋{{.request_uri }} 🌍{{.cf_ipcountry}} {{.cf_connecting_ip}} 🆔{{.cf_ray}} 💻{{.user_agent }}\""
    },
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_method=\"POST\" | status=~\"200|201|202|204\" | accept=~\".*application/json.*\" | line_format \"✉️ {{.request_method}} 📋{{.request_uri }} 🌍{{.cf_ipcountry}} {{.cf_connecting_ip}} 🆔{{.cf_ray}} 💻{{.user_agent }}\""
    }
   ]
  },
  { "title": "Stats Overtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Paste - GET/POST Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_method=\"GET\" | accept=~\".*application/json.*\" |  __error__=\"\" [$__interval]))",
     "legendFormat": "GET Status Code {{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_method=\"POST\" | accept=~\".*application/json.*\" |  __error__=\"\" [$__interval]))",
     "legendFormat": "POST Status Code {{ status }}"
    }
   ]
  },
  {
   "title": "Paste - Body Bytes Send",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_method=~\"GET|POST\" | accept=~\".*application/json.*\" | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent {{ body_bytes_sent }}"
    }
   ]
  },
  { "title": "Other Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Paste - Top 10 User Agents",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "topk(10, sum by (user_agent) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | accept=~\".*application/json.*\" | __error__=\"\" [$__range])))",
     "legendFormat": "User Agent: {{ user_agent }}"
    }
   ]
  },
  {
   "title": "Paste - Top 10 Requested Paste by IP and Country",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 32 },
   "targets": [
    {
     "expr": "topk(10, sum by (cf_connecting_ip,cf_ipcountry) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_uri=~\".*pasteid=.*\" | request_method=\"GET\" | accept=~\".*application/json.*\" | __error__=\"\" [$__range])))",
     "legendFormat": "Top Visitors: {{ cf_connecting_ip }} {{ cf_ipcountry }}"
    }
   ]
  },
  {
   "title": "Paste - Top 15 Requested Paste",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "topk(15, sum by (request_uri) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_uri=~\".*pasteid=.*\" | request_method=\"GET\" | accept=~\".*application/json.*\" | __error__=\"\" [$__range])))",
     "legendFormat": "Requested Paste: {{ request_uri }}"
    }
   ]
  },
  {
   "title": "Paste - Top 15 Referer",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 41 },
   "targets": [
    {
     "expr": "topk(15, sum by (referer) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_uri=~\".*pasteid=.*\" | request_method=\"GET\" | accept=~\".*application/json.*\" | __error__=\"\" [$__range])))",
     "legendFormat": "Referer: {{ referer }}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Paste by Country",
   "type": "table",
   "gridPos": { "h": 13, "w": 3, "x": 14, "y": 41 },
   "targets": [
    {
     "expr": "topk(10, sum by (cf_ipcountry) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | request_uri=~\".*pasteid=.*\" | request_method=\"GET\" | accept=~\".*application/json.*\" | __error__=\"\" [$__range])))",
     "legendFormat": "Country: {{ cf_ipcountry }}"
    }
   ]
  }
 ]
}