{
 "title": "SUDO Logs - JSON version",
 "description": "Monitor SUDO Logs with JSON Logging",
 "tags": [
  "linux",
  "loki",
  "sudo"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "label_name",
    "label": "Label Name",
    "query": {}
   },
   {
    "name": "label_value",
    "label": "Label Value",
    "query": {}
   },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Total Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Accepted SUDO Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"accept\\\":{.*\" | __error__=\"\" [$__range])"
    }
   ]
  },
  {
   "title": "Total Rejected SUDO Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"reject\\\":{.*\" | __error__=\"\" [$__range])"
    }
   ]
  },
  {
   "title": "SUDO Log Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"reject\\\":{.*|.+{\\\"accept\\\":{.*\" | __error__=\"\" [$__range])"
    }
   ]
  },
  {
   "title": "SUDO Log in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"reject\\\":{.*|.+{\\\"accept\\\":{.*\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": {
    "content": "# SUDO JSON Log\n\nCreated by [VoidQuark](https://voidquark.com)\n\n- [Dashboard Source](https://github.com/voidquark/grafana-dashboards)\n\n- Follow me on [X](https://x.com/voidquark) for updates on new and current dashboards."
   }
  },
  {
   "title": "Accepted SUDO Events by User",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(sudo_accept_submituser) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"accept\\\":{.*\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{ sudo_accept_submituser }}"
    }
   ]
  },
  {
   "title": "Rejected SUDO Events by User",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(sudo_reject_submituser) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"reject\\\":{.*\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{ sudo_reject_submituser }}"
    }
   ]
  },
  {
   "title": "SUDO Recent Log",
   "type": "logs",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"accept\\\":{.*\" | json runargv=\"sudo.accept.runargv\" | line_format\"👤 {{ .sudo_accept_submituser }} 📂 {{ .sudo_accept_submitcwd }} 🎯 {{ .sudo_accept_runuser }} 🖥️ {{ .runargv }}\" | __error__=\"\""
    },
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\"^{\\\"reject\\\":{.*\" | json runargv=\"reject.runargv\" | line_format\"🚫 {{ .sudo_reject_reason }} 👤 {{ .sudo_reject_submituser }} 📂 {{ .sudo_reject_submitcwd }} 🎯 {{ .sudo_reject_runuser }} 🖥️ {{ .runargv }}\" | __error__=\"\""
    }
   ]
  },
  { "title": "Accepted SUDO Events - Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Accepted SUDO Events Details",
   "type": "table",
   "gridPos": { "h": 21, "w": 23, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"accept\\\":{.*\" | json runargv=\"sudo.accept.runargv\" | __error__=\"\""
    }
   ]
  },
  {
   "title": "Top 10 Accepted SUDO Events by User and Command",
   "type": "table",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "topk(10, sum by (sudo_accept_submituser, runargv) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"accept\\\":{.*\" | json runargv=\"sudo.accept.runargv\" | __error__=\"\" [$__range])))",
     "legendFormat": "{{ sudo_accept_submituser }} {{ runargv }}"
    }
   ]
  },
  { "title": "Rejected SUDO Events - Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Rejected SUDO Events Details",
   "type": "table",
   "gridPos": { "h": 21, "w": 23, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"reject\\\":{.*\" | json runargv=\"sudo.reject.runargv\" | __error__=\"\""
    }
   ]
  },
  {
   "title": "Top 10 Rejected SUDO Events by User and Command",
   "type": "table",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "topk(10, sum by (sudo_reject_submituser, runargv) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"reject\\\":{.*\" | json runargv=\"sudo.reject.runargv\" | __error__=\"\" [$__range])))",
     "legendFormat": "{{ sudo_reject_submituser }} {{ runargv }}"
    }
   ]
  }
 ]
}